[package]
name = "waybar-weather"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.33"
reqwest = { version = "0.13.4", features = ["json", "rustls", "query"] }
serde = "1.0.229"
serde_json = "1.0.151"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros", "time"] }
zbus = "5.18.0"


